// ── Yi Jin Jing · Muscle-Tendon Changing Classic ────────────────
// Fixed choreography: scales by DEPTH · BREATH · DURATION, not reps.

export const YIJINJING = [
  { id: 1,  name: "Wei Tuo Presenting the Pestle I",   zh: "韦驮献杵 (一)",
    action: "Stand rooted; draw both palms together at the chest in anjali; sink the breath to the dantian.",
    target: "Centering · breath · chest", videoId: null,
    cue: "Shoulders melt down, spine long — three slow breaths before you move." },
  { id: 2,  name: "Wei Tuo Presenting the Pestle II",  zh: "韦驮献杵 (二)",
    action: "Extend both arms to shoulder height, palms turn out and push, fingers spread wide.",
    target: "Shoulders · arms · wrists", videoId: null,
    cue: "Reach through the fingertips; keep the collarbones broad." },
  { id: 3,  name: "Wei Tuo Presenting the Pestle III", zh: "韦驮献杵 (三)",
    action: "Press both palms overhead, rise onto the toes — 'holding up the heavens'.",
    target: "Front line · calves · spine", videoId: null,
    cue: "Push the sky up and the floor down at once; lengthen, don't arch." },
  { id: 4,  name: "Plucking a Star, Exchanging a Star Cluster", zh: "摘星换斗势",
    action: "One cupped palm overhead, gaze up at it; the other hand rests at the mingmen. Alternate sides.",
    target: "Spinal rotation · side-bend · shoulder", videoId: null,
    cue: "Let the eyes lead the spiral; the low hand stays soft on the low back." },
  { id: 5,  name: "Pulling Nine Oxen by Their Tails",  zh: "倒拽九牛尾势",
    action: "Bow stance; front and back arms reach as if hauling a rope, torso twisting, hands gripping.",
    target: "Grip · forearm · waist · legs", videoId: null,
    cue: "Pull from the waist, not the arms; feel the whole spiral load." },
  { id: 6,  name: "Showing Talons and Spreading Wings", zh: "出爪亮翅势",
    action: "Tiger-claw palms push forward from the chest, then draw slowly back on the in-breath.",
    target: "Chest · finger tendons · breath", videoId: null,
    cue: "Exhale into the push, inhale to reel it back — tension then release." },
  { id: 7,  name: "Nine Ghosts Drawing Sabers",         zh: "九鬼拔马刀势",
    action: "One arm wraps the head to the far ear, the other reaches behind the back; twist and side-bend. Alternate.",
    target: "Deep spinal rotation · shoulder · neck", videoId: null,
    cue: "Wrap, then open the chest into the turn — go only as far as breath stays smooth." },
  { id: 8,  name: "Three Plates Falling to the Floor",  zh: "三盘落地势",
    action: "Horse stance; palms press down as you sink, then rise turning palms up (exhale on the sink).",
    target: "Legs · grounding · breath", videoId: null,
    cue: "The big leg loader — knees track the toes, weight in the whole foot." },
  { id: 9,  name: "Black Dragon Displaying Its Claws",  zh: "青龙探爪势",
    action: "A claw hand reaches across the body, then sweeps down toward the opposite foot. Alternate.",
    target: "Lateral line · hamstrings · rotation", videoId: null,
    cue: "Reach first, fold second; keep the crown of the head chasing the hand." },
  { id: 10, name: "Tiger Pouncing on Its Prey",         zh: "卧虎扑食势",
    action: "Deep lunge, fingertips to the floor; the spine undulates forward like a pounce, then withdraws.",
    target: "Spinal wave · wrists · hip flexors · core", videoId: null,
    cue: "Most athletic shape — from the knees first if the wrists complain." },
  { id: 11, name: "Bowing Down",                        zh: "打躬势",
    action: "Hands cover the ears; fold from the hips into a deep bow, rolling down vertebra by vertebra, then roll up.",
    target: "Full spinal flexion · back line · hamstrings", videoId: null,
    cue: "Soften the knees; let the head hang heavy at the bottom before you rise." },
  { id: 12, name: "Wagging the Tail",                   zh: "掉尾势",
    action: "Hands interlaced pressing toward the floor; torso swings and rotates side to side, tailbone leading.",
    target: "Rotation · flexion · integration", videoId: null,
    cue: "Small and unforced — this settles the form, it isn't a stretch to win." },
];

export const YIJINJING_SESSION = {
  label: "Yi Jin Jing · Muscle-Tendon Changing",
  subtitle: "Soft/internal Shaolin — Lunar day anchor, before Tai Chi",
  breaths: [3, 6, 9],
  legDepth: ["quarter squat", "half squat", "thighs parallel"],
  rounds: ["form once, slow — learn the shapes",
           "full form, full range — load the tendons",
           "full form + a 2nd round of movements 5 · 8 · 10, with intention leading the Qi"],
  minutes: [20, 30, 40],
  focus: ["Learn the 12 shapes and the breath.",
          "Deepen range and hold the loaded postures.",
          "Extend holds, add the internal (yi → qi) lead."],
};
